### ISSUE TITLE
Schema validation: Property 'extends' is not allowed

### ISSUE THREAD

**Issue by azertypow** [bnomei/kirby3-schema#24]
<img width="817" alt="image" src="https://github.com/bnomei/kirby3-schema/assets/12177073/3b1fdc91-61ba-4721-a34d-6ccead573e69">

**Comment by bnomei** [comment]
thanks @azertypow 

`extends` is kind of an edge case for the schema. it can neither validate what you are extending from not can it allow the other props to be checked when it is used. for that reason i had decided to "flag" extends as kind of dangerous by making them not allowed. 

so its not perfect but intended behaviour.
