### ISSUE TITLE
Use file paths to deduce schema types

### ISSUE THREAD

**Issue by yandodov** [bnomei/kirby3-schema#6]
Regarding [this](https://github.com/bnomei/kirby3-schema/blob/9cc0a6f5da65d763aa8fd5da92f8ff8bfa4a6952/README.md?plain=1#L56):

> Since Kirby reuses some types like `file`, `info`, `pages` in fields and sections the schema can not always determine which blueprint you are working on with absolute certainty. For now I introduced a `blueprint` property to solve this. Use it in your `file`, `page`, `user` and `site` blueprints.

Couldn't you have different schemas based on the filetype? For example:

```diff
- "/path/to/your/schema/kirby3-blueprints.schema.json": "site/blueprints/**/*.yml"
+ "/path/to/your/schema/kirby3-site.schema.json": "site/blueprints/site.yml",
+ "/path/to/your/schema/kirby3-page.schema.json": "site/blueprints/pages/**/*.yml"
```

…or am I missing something?

**Comment by bnomei** [comment]
that really is more for the local dev. the final goal would be a single file for the [json schema store](https://www.schemastore.org/json/). so that's what i am aiming for as well.
